export const editorModes = [
    "abap", "abc", "actionscript", "ada", "alda", "apache_conf", "apex", "applescript",
    "aql", "asciidoc", "asl", "autohotkey", "batchfile", "c9search", "assembly_x86",
    "c_cpp", "cirru", "clojure", "cobol", "coffee", "coldfusion", "crystal", "csharp",
    "csp", "css", "curly", "d", "dart", "diff", "django", "dockerfile", "dot", "drools",
    "edifact", "eiffel", "ejs", "elixir", "elm", "erlang", "forth", "fortran", "fsharp",
    "fsl", "ftl", "gcode", "gherkin", "gitignore", "glsl", "gobstones", "golang",
    "graphqlschema", "groovy", "haml", "handlebars", "haskell", "haxe", "hjson", "html",
    "ini", "io", "jack", "jade", "java", "javascript", "json", "jsoniq", "jsp", "jssm",
    "jsx", "julia", "kotlin", "latex", "latte", "less", "liquid", "lisp", "livescript",
    "logiql", "logtalk", "lsl", "lua", "luapage", "lucene", "makefile", "markdown", "mask",
    "matlab", "maze", "mediawiki", "mel", "mips", "mixal", "mushcode", "mysql", "nginx",
    "nim", "nix", "nsis", "nunjucks", "objectivec", "ocaml", "pascal", "perl", "pgsql", "php",
    "php_laravel_blade", "pig", "plain_text", "powershell", "praat", "prisma", "prolog",
    "properties", "protobuf", "puppet", "python", "qml", "r", "raku", "razor", "rdoc",
    "red", "redshift", "rhtml", "rst", "ruby", "rust", "sass", "scad", "scala", "scheme",
    "scrypt", "scss", "sh", "sjs", "slim", "smarty", "smithy", "snippets", "space", "sparql",
    "sql", "sqlserver", "stylus", "svg", "swift", "tcl", "terraform", "tex", "text", "textile",
    "toml", "tsx", "turtle", "twig", "typescript", "vala", "vbscript", "velocity", "verilog",
    "vhdl", "visualforce", "wollok", "xml", "xquery", "yaml", "zeek"
];

export const fallbackEditorMode = "text";

export const editorThemes = [
    "ambiance",
    "chaos",
    "chrome",
    "clouds",
    "clouds_midnight",
    "cobalt",
    "crimson_editor",
    "dawn",
    "dracula",
    "dreamweaver",
    "eclipse",
    "github",
    "gob",
    "gruvbox",
    "idle_fingers",
    "iplastic",
    "katzenmilch",
    "kr_theme",
    "kuroir",
    "merbivore",
    "merbivore_soft",
    "mono_industrial",
    "monokai",
    "nord_dark",
    "one_dark",
    "pastel_on_dark",
    "solarized_dark",
    "solarized_light",
    "sqlserver",
    "terminal",
    "textmate",
    "tomorrow",
    "tomorrow_night_blue",
    "tomorrow_night_bright",
    "tomorrow_night",
    "tomorrow_night_eighties",
    "twilight",
    "vibrant_ink",
    "xcode"
];

export const defaultEditorTheme = "github"

const syntaxMapping = {
    "go": "golang",
    "apacheconf": "apache_conf"
}

export const resolveSyntax = (syntax) => {
    if (editorModes.includes(syntax)) {
        return syntax;
    }

    if (syntaxMapping.hasOwnProperty(syntax)) {
        return syntaxMapping[syntax]
    }

    return fallbackEditorMode;
}

export const extensionToLanguage = {
    "abap": "abap",
    "mod": "xml",
    "apacheconf": "apache_conf",
    "vhost": "apache_conf",
    "asp": "csharp",
    "asax": "csharp",
    "ascx": "csharp",
    "ashx": "csharp",
    "asmx": "csharp",
    "aspx": "csharp",
    "axd": "csharp",
    "as": "actionscript",
    "adb": "ada",
    "ada": "ada",
    "ads": "ada",
    "raku": "raku",
    "applescript": "applescript",
    "scpt": "applescript",
    "asciidoc": "asciidoc",
    "adoc": "asciidoc",
    "asm": "assembly_x86",
    "a51": "assembly_x86",
    "nasm": "assembly_x86",
    "ahk": "autohotkey",
    "ahkl": "autohotkey",
    "bat": "batchfile",
    "cmd": "batchfile",
    "c": "c_cpp",
    "cats": "c_cpp",
    "h": "objectivec",
    "idc": "c_cpp",
    "w": "c_cpp",
    "cshtml": "csharp",
    "csx": "csharp",
    "cpp": "c_cpp",
    "c++": "c_cpp",
    "cc": "c_cpp",
    "cxx": "c_cpp",
    "h++": "c_cpp",
    "hpp": "c_cpp",
    "hxx": "c_cpp",
    "inl": "c_cpp",
    "ipp": "c_cpp",
    "tcc": "c_cpp",
    "tpp": "c_cpp",
    "chs": "haskell",
    "cob": "cobol",
    "cbl": "cobol",
    "ccp": "cobol",
    "cobol": "cobol",
    "cpy": "cobol",
    "css": "css",
    "cirru": "cirru",
    "clj": "clojure",
    "boot": "clojure",
    "cl2": "clojure",
    "cljc": "clojure",
    "cljs": "clojure",
    "cljs.hl": "clojure",
    "cljscm": "clojure",
    "cljx": "clojure",
    "hic": "clojure",
    "cfm": "coldfusion",
    "cfml": "coldfusion",
    "cfc": "coldfusion",
    "lisp": "lisp",
    "asd": "lisp",
    "l": "lisp",
    "lsp": "lisp",
    "ny": "lisp",
    "podsl": "lisp",
    "sexp": "lisp",
    "v": "verilog",
    "cr": "crystal",
    "pyx": "python",
    "pxd": "python",
    "pxi": "python",
    "d": "makefile",
    "di": "d",
    "dart": "dart",
    "diff": "diff",
    "patch": "diff",
    "dockerfile": "dockerfile",
    "e": "eiffel",
    "ex": "elixir",
    "exs": "elixir",
    "elm": "elm",
    "el": "lisp",
    "emacs": "lisp",
    "emacs.desktop": "lisp",
    "erl": "erlang",
    "es": "javascript",
    "escript": "erlang",
    "hrl": "erlang",
    "xrl": "erlang",
    "yrl": "erlang",
    "fs": "glsl",
    "fsi": "fsharp",
    "fsx": "fsharp",
    "f90": "fortran",
    "f": "forth",
    "f03": "fortran",
    "f08": "fortran",
    "f77": "fortran",
    "f95": "fortran",
    "for": "forth",
    "fpp": "fortran",
    "fth": "forth",
    "4th": "forth",
    "forth": "forth",
    "fr": "text",
    "log": "text",
    "frt": "forth",
    "gco": "gcode",
    "gcode": "gcode",
    "glsl": "glsl",
    "fp": "glsl",
    "frag": "javascript",
    "frg": "glsl",
    "fsh": "glsl",
    "fshader": "glsl",
    "geo": "glsl",
    "geom": "glsl",
    "glslv": "glsl",
    "gshader": "glsl",
    "shader": "glsl",
    "vert": "glsl",
    "vrx": "glsl",
    "vsh": "glsl",
    "vshader": "glsl",
    "gml": "xml",
    "gs": "javascript",
    "dot": "dot",
    "gv": "dot",
    "groovy": "groovy",
    "grt": "groovy",
    "gtpl": "groovy",
    "gvy": "groovy",
    "gsp": "groovy",
    "html": "html",
    "htm": "html",
    "xht": "html",
    "xhtml": "html",
    "php": "php",
    "haml": "haml",
    "handlebars": "handlebars",
    "hbs": "handlebars",
    "hs": "haskell",
    "hsc": "haskell",
    "hx": "haxe",
    "hxsl": "haxe",
    "ini": "ini",
    "cfg": "ini",
    "prefs": "ini",
    "properties": "ini",
    "json": "json",
    "geojson": "json",
    "lock": "json",
    "topojson": "json",
    "jq": "jsoniq",
    "jsx": "jsx",
    "jade": "jade",
    "java": "java",
    "js": "javascript",
    "_js": "javascript",
    "bones": "javascript",
    "es6": "javascript",
    "jake": "javascript",
    "jsb": "javascript",
    "jscad": "javascript",
    "jsfl": "javascript",
    "jsm": "javascript",
    "jss": "javascript",
    "njs": "javascript",
    "pac": "javascript",
    "sjs": "javascript",
    "ssjs": "javascript",
    "sublime-build": "javascript",
    "sublime-commands": "javascript",
    "sublime-completions": "javascript",
    "sublime-keymap": "javascript",
    "sublime-macro": "javascript",
    "sublime-menu": "javascript",
    "sublime-mousemap": "javascript",
    "sublime-project": "javascript",
    "sublime-settings": "javascript",
    "sublime-theme": "javascript",
    "sublime-workspace": "javascript",
    "sublime_metrics": "javascript",
    "sublime_session": "javascript",
    "xsjs": "javascript",
    "xsjslib": "javascript",
    "jl": "julia",
    "kt": "kotlin",
    "ktm": "kotlin",
    "kts": "kotlin",
    "lsl": "lsl",
    "lslp": "lsl",
    "latte": "latte",
    "less": "less",
    "m": "objectivec",
    "liquid": "liquid",
    "_ls": "livescript",
    "lgt": "logtalk",
    "logtalk": "logtalk",
    "lua": "lua",
    "nse": "lua",
    "pd_lua": "lua",
    "rbxs": "lua",
    "wlua": "lua",
    "mak": "makefile",
    "mk": "makefile",
    "mkfile": "makefile",
    "md": "markdown",
    "markdown": "markdown",
    "mkd": "markdown",
    "mkdn": "markdown",
    "mkdown": "markdown",
    "ron": "markdown",
    "mask": "mask",
    "nb": "text",
    "matlab": "matlab",
    "mediawiki": "mediawiki",
    "wiki": "mediawiki",
    "ncl": "text",
    "nsi": "nsis",
    "nsh": "nsis",
    "nginxconf": "nginx",
    "nix": "nix",
    "ml": "ocaml",
    "eliom": "ocaml",
    "eliomi": "ocaml",
    "ml4": "ocaml",
    "mli": "ocaml",
    "mll": "ocaml",
    "mly": "ocaml",
    "mm": "xml",
    "aw": "php",
    "ctp": "php",
    "php3": "php",
    "php4": "php",
    "php5": "php",
    "phps": "php",
    "phpt": "php",
    "pas": "pascal",
    "dfm": "pascal",
    "dpr": "pascal",
    "lpr": "pascal",
    "pp": "puppet",
    "pl": "prolog",
    "al": "perl",
    "perl": "perl",
    "ph": "perl",
    "plx": "perl",
    "pm": "raku",
    "psgi": "perl",
    "6pl": "raku",
    "6pm": "raku",
    "nqp": "raku",
    "p6": "raku",
    "p6l": "raku",
    "p6m": "raku",
    "pl6": "raku",
    "pm6": "raku",
    "ps1": "powershell",
    "psd1": "powershell",
    "psm1": "powershell",
    "prolog": "prolog",
    "yap": "prolog",
    "py": "python",
    "bzl": "python",
    "gyp": "python",
    "lmi": "python",
    "pyde": "python",
    "pyp": "python",
    "pyt": "python",
    "pyw": "python",
    "tac": "python",
    "wsgi": "python",
    "xpy": "python",
    "qml": "qml",
    "qbs": "qml",
    "rd": "r",
    "rsx": "r",
    "rdoc": "rdoc",
    "rhtml": "rhtml",
    "red": "red",
    "reds": "red",
    "rs": "rust",
    "rb": "ruby",
    "builder": "ruby",
    "gemspec": "ruby",
    "god": "ruby",
    "go": "golang",
    "irbrc": "ruby",
    "jbuilder": "ruby",
    "mspec": "ruby",
    "pluginspec": "xml",
    "podspec": "ruby",
    "rabl": "ruby",
    "rake": "ruby",
    "rbuild": "ruby",
    "rbw": "ruby",
    "rbx": "ruby",
    "ru": "ruby",
    "ruby": "ruby",
    "thor": "ruby",
    "watchr": "ruby",
    "rs.in": "rust",
    "scss": "scss",
    "sparql": "sparql",
    "rq": "sparql",
    "cql": "sql",
    "ddl": "sql",
    "prc": "sql",
    "tab": "sql",
    "udf": "sql",
    "viw": "sql",
    "svg": "svg",
    "sls": "scheme",
    "sass": "sass",
    "scala": "scala",
    "sbt": "scala",
    "scm": "scheme",
    "sld": "scheme",
    "sps": "scheme",
    "ss": "scheme",
    "slim": "slim",
    "tpl": "smarty",
    "styl": "stylus",
    "swift": "swift",
    "toml": "toml",
    "tcl": "tcl",
    "adp": "tcl",
    "tm": "tcl",
    "tex": "tex",
    "aux": "tex",
    "bbx": "tex",
    "bib": "tex",
    "cbx": "tex",
    "dtx": "tex",
    "ins": "tex",
    "lbx": "tex",
    "ltx": "tex",
    "mkii": "tex",
    "mkiv": "tex",
    "mkvi": "tex",
    "sty": "tex",
    "toc": "tex",
    "txt": "text",
    "no": "text",
    "textile": "textile",
    "ttl": "turtle",
    "twig": "twig",
    "ts": "xml",
    "tsx": "xml",
    "vhdl": "vhdl",
    "vhd": "vhdl",
    "vhf": "vhdl",
    "vhi": "vhdl",
    "vho": "vhdl",
    "vhs": "vhdl",
    "vht": "vhdl",
    "vhw": "vhdl",
    "vala": "vala",
    "vapi": "vala",
    "veo": "verilog",
    "xml": "xml",
    "ant": "xml",
    "axml": "xml",
    "ccxml": "xml",
    "clixml": "xml",
    "cproject": "xml",
    "csl": "xml",
    "csproj": "xml",
    "ct": "xml",
    "dita": "xml",
    "ditamap": "xml",
    "ditaval": "xml",
    "dll.config": "xml",
    "dotsettings": "xml",
    "filters": "xml",
    "fsproj": "xml",
    "fxml": "xml",
    "glade": "xml",
    "grxml": "xml",
    "iml": "xml",
    "ivy": "xml",
    "jelly": "xml",
    "jsproj": "xml",
    "kml": "xml",
    "launch": "xml",
    "mdpolicy": "xml",
    "mxml": "xml",
    "nproj": "xml",
    "nuspec": "xml",
    "odd": "xml",
    "osm": "xml",
    "plist": "xml",
    "props": "xml",
    "ps1xml": "xml",
    "psc1": "xml",
    "pt": "xml",
    "rdf": "xml",
    "rss": "xml",
    "scxml": "xml",
    "srdf": "xml",
    "storyboard": "xml",
    "stTheme": "xml",
    "sublime-snippet": "xml",
    "targets": "xml",
    "tmCommand": "xml",
    "tml": "xml",
    "tmLanguage": "xml",
    "tmPreferences": "xml",
    "tmSnippet": "xml",
    "tmTheme": "xml",
    "ui": "xml",
    "urdf": "xml",
    "ux": "xml",
    "vbproj": "xml",
    "vcxproj": "xml",
    "vssettings": "xml",
    "vxml": "xml",
    "wsdl": "xml",
    "wsf": "xml",
    "wxi": "xml",
    "wxl": "xml",
    "wxs": "xml",
    "x3d": "xml",
    "xacro": "xml",
    "xaml": "xml",
    "xib": "xml",
    "xlf": "xml",
    "xliff": "xml",
    "xmi": "xml",
    "xml.dist": "xml",
    "xproj": "xml",
    "xsd": "xml",
    "xul": "xml",
    "zcml": "xml",
    "xquery": "xquery",
    "xq": "xquery",
    "xql": "xquery",
    "xqm": "xquery",
    "xqy": "xquery",
    "yml": "yaml",
    "reek": "yaml",
    "rviz": "yaml",
    "sublime-syntax": "yaml",
    "syntax": "yaml",
    "yaml": "yaml",
    "yaml-tmlanguage": "yaml",
    "rst": "rst",
    "rest": "rst"
}
